// The Nursery Green — Product Catalog (synced with website)
const BACKEND_URL = 'https://backend-production-f128.up.railway.app';
const IMAGE_BASE_URL = 'https://thenurserygreen.com';

export const PRODUCTS = [
  {
    id: '1',
    name: 'Vermi Compost',
    price: 150,
    category: 'Fertilizer',
    description: 'Rich in nutrients and beneficial microbes, our Vermi Compost is perfect for nurturing your plants. Made from decomposed organic matter using earthworms, it improves soil structure and promotes healthy plant growth.',
    image: `${IMAGE_BASE_URL}/Images/Vermi%20Compost.jpg`,
    rating: 4.85,
    reviews: 128,
    weight: '2 kg',
    inStock: true,
    benefits: ['Increases soil fertility', 'Improves water retention', 'Enhances plant growth', '100% Organic', 'Eco-friendly', 'Reduces need for chemical fertilizers'],
    usage: 'Mix 2-4 kg with soil before planting. For existing plants, mix 1-2 kg with top soil layer. Use quarterly for best results.',
    type: 'Organic Fertilizer',
  },
  {
    id: '2',
    name: 'Neem Cake Powder',
    price: 150,
    category: 'Pest Control',
    description: 'Natural pest control solution derived from neem kernels. Neem cake powder is rich in nitrogen and acts as both a fertilizer and pesticide, making it perfect for organic gardening.',
    image: `${IMAGE_BASE_URL}/Images/Neem%20Cake%20Powder.jpg`,
    rating: 4.89,
    reviews: 95,
    weight: '1 kg',
    inStock: true,
    benefits: ['Controls common garden pests', 'Enriches soil with nitrogen', 'Improves soil microbial activity', 'Safe for beneficial insects', '100% Natural', 'Prevents fungal diseases'],
    usage: 'Mix 500g per square meter into soil. For pest control, spray 2-3% solution weekly. Apply in early morning or late evening.',
    type: 'Bio Pesticide & Fertilizer',
  },
  {
    id: '3',
    name: 'Flower Mixture',
    price: 130,
    category: 'Fertilizer',
    description: 'Specially formulated blend for flowering plants. Rich in phosphorus and potassium to promote abundant blooms and vibrant colors throughout the season.',
    image: `${IMAGE_BASE_URL}/Images/Flower%20Mixture.png`,
    rating: 4.92,
    reviews: 76,
    weight: '1 kg',
    inStock: true,
    benefits: ['Promotes flowering', 'Enhances bloom color', 'Strengthens flower stems', 'Increases flower count', 'Balanced nutrition', 'Extends flowering season'],
    usage: 'Apply 2 tablespoons per plant monthly. Mix with soil or make a liquid solution. Apply every 4-6 weeks during growing season.',
    type: 'Flowering Plant Fertilizer',
  },
  {
    id: '4',
    name: 'All in One Mixture',
    price: 130,
    category: 'Multipurpose',
    description: 'Complete plant nutrition in one pack. This balanced organic mixture contains essential macro and micronutrients needed by all types of plants - flowers, vegetables, fruits, and ornamentals.',
    image: `${IMAGE_BASE_URL}/Images/All%20in%20one%20mixture.png`,
    rating: 4.76,
    reviews: 142,
    weight: '2 kg',
    inStock: true,
    benefits: ['Universal for all plants', 'Balanced NPK ratio', 'Complete nutrition', 'Improves soil quality', 'Safe for all plant types', 'Long-lasting effect'],
    usage: 'Mix 1-2 kg with potting soil. For existing plants, apply 50g per plant monthly. Water after application for best results.',
    type: 'All-Purpose Organic Fertilizer',
  },
  {
    id: '5',
    name: 'Plant Booster Spray',
    price: 230,
    category: 'Spray',
    description: 'Liquid plant supplement for vigorous growth. Contains amino acids and growth promoters that accelerate vegetative growth and make your plants fuller and bushier.',
    image: `${IMAGE_BASE_URL}/Images/Plant%20Booster%20Spray.png`,
    rating: 4.88,
    reviews: 63,
    weight: '500 ml',
    inStock: true,
    benefits: ['Accelerates plant growth', 'Fuller foliage', 'Longer stems', 'Improves leaf color', 'Easy to use spray', 'Fast visible results'],
    usage: 'Dilute 10ml in 1 liter water. Spray on leaves and soil weekly. Best applied in evening for optimal absorption.',
    type: 'Plant Growth Supplement',
  },
  {
    id: '6',
    name: 'Flower Booster Spray',
    price: 230,
    category: 'Spray',
    description: 'Premium flower enhancement spray. Loaded with phosphorus and potassium to trigger flowering, increase bud formation, and intensify flower color and fragrance.',
    image: `${IMAGE_BASE_URL}/Images/Flower%20Booster%20Spray.png`,
    rating: 4.91,
    reviews: 88,
    weight: '500 ml',
    inStock: true,
    benefits: ['Increases flower count', 'Enhances fragrance', 'Vibrant colors', 'Longer blooming period', 'Bigger flowers', 'Prevents bud drop'],
    usage: 'Dilute 15ml in 1 liter water. Spray weekly during budding season. Apply in early morning for best results.',
    type: 'Flower Enhancement Spray',
  },
  {
    id: '7',
    name: 'Plant Protection Spray',
    price: 230,
    category: 'Spray',
    description: 'Comprehensive plant protection against common pests and diseases. Organic formula that protects without harming beneficial insects or your plants.',
    image: `${IMAGE_BASE_URL}/Images/Plant%20Booster%20Spray%20(2).png`,
    rating: 4.79,
    reviews: 54,
    weight: '500 ml',
    inStock: true,
    benefits: ['Controls mites and insects', 'Prevents fungal infections', 'Safe for edible plants', 'No harmful chemicals', 'Protects overall plant health', 'Natural composition'],
    usage: 'Dilute 20ml in 1 liter water. Spray all leaf surfaces weekly. For heavy infestation, spray every 3-4 days.',
    type: 'Organic Pest & Disease Control',
  },
  {
    id: '8',
    name: 'Neem Oil',
    price: 150,
    category: 'Pest Control',
    description: 'Pure cold-pressed neem oil. Effective against a wide range of pests and fungal infections. Completely natural and safe for all plants and beneficial insects.',
    image: `${IMAGE_BASE_URL}/Images/Neem%20Oil.png`,
    rating: 4.87,
    reviews: 112,
    weight: '250 ml',
    inStock: true,
    benefits: ['Kills soft-bodied insects', 'Prevents fungal diseases', 'Safe for beneficial insects', '100% Natural', 'Non-toxic', 'Multi-purpose'],
    usage: 'Dilute 5-10ml in 1 liter water with few drops of dish wash liquid. Spray thoroughly on all plant parts. Apply in evening for best results.',
    type: 'Pure Organic Neem Oil',
  },
  {
    id: '9',
    name: 'Root Booster',
    price: 150,
    category: 'Root Growth',
    description: 'Specialized organic formula to promote strong and healthy root development. Perfect for both seedlings and established plants to encourage deeper root systems.',
    image: `${IMAGE_BASE_URL}/Images/Bone%20Meal.jpg`,
    rating: 4.90,
    reviews: 47,
    weight: '800 g',
    inStock: true,
    benefits: ['Promotes root growth', 'Strengthens plant base', 'Improves nutrient uptake', 'Increases plant stability', 'Organic source', 'Better transplant survival'],
    usage: 'Mix 2-3 tablespoons per plant hole during planting. For existing plants, apply 1 tablespoon per month to soil surface. Water well after application.',
    type: 'Root Growth Enhancer',
  },
  {
    id: '10',
    name: 'Plant Diet',
    price: 150,
    category: 'Nutrient',
    description: 'Complete dietary supplement for plants with all essential micro and macronutrients. Formulated to address nutritional deficiencies and maintain overall plant health.',
    image: `${IMAGE_BASE_URL}/Images/Flower%20mixture%202.png`,
    rating: 4.77,
    reviews: 69,
    weight: '500 g',
    inStock: true,
    benefits: ['Prevents nutrient deficiencies', 'Promotes healthy growth', 'Improves immunity', 'Enhances foliage color', 'Safe for all plant types', 'Long-lasting nutrition'],
    usage: 'Dissolve 1 teaspoon in 1 liter water. Apply once every 2 weeks. Can also be mixed with soil at planting time.',
    type: 'Complete Plant Nutrition',
  },
];

export const CATEGORIES = [
  'All',
  'Fertilizer',
  'Pest Control',
  'Spray',
  'Multipurpose',
  'Root Growth',
  'Nutrient',
];

// Shipping rates from Lucknow
export const SHIPPING_RATES = {
  'Uttar Pradesh': 40,
  'Madhya Pradesh': 60,
  'Rajasthan': 70,
  'Delhi': 50,
  'Haryana': 60,
  'Bihar': 70,
  'Jharkhand': 80,
  'Maharashtra': 90,
  'Gujarat': 90,
  'Tamil Nadu': 120,
  'Karnataka': 110,
  'Kerala': 130,
  'West Bengal': 80,
  'Punjab': 70,
  'Uttarakhand': 50,
  'Chhattisgarh': 70,
  'Odisha': 90,
  'Assam': 120,
  'Other': 100,
};

export const FREE_SHIPPING_THRESHOLD = 1999;

export const STATES = Object.keys(SHIPPING_RATES);

export const COMMUNITY_CATEGORIES = [
  { key: 'all', label: 'All', icon: 'apps' },
  { key: 'show-tell', label: 'Show & Tell', icon: 'camera' },
  { key: 'help', label: 'Help', icon: 'help-circle' },
  { key: 'tips', label: 'Tips', icon: 'bulb' },
  { key: 'diy', label: 'DIY', icon: 'construct' },
  { key: 'balcony', label: 'Balcony', icon: 'sunny' },
  { key: 'terrace', label: 'Terrace', icon: 'home' },
  { key: 'indoor', label: 'Indoor', icon: 'leaf' },
  { key: 'organic', label: 'Organic', icon: 'nutrition' },
];

export const ORDER_STATUSES = {
  pending: { label: 'Pending', color: '#FF9800' },
  confirmed: { label: 'Confirmed', color: '#1E88E5' },
  processing: { label: 'Processing', color: '#7B1FA2' },
  shipped: { label: 'Shipped', color: '#00897B' },
  delivered: { label: 'Delivered', color: '#43A047' },
  cancelled: { label: 'Cancelled', color: '#E53935' },
};
