// The Nursery Green — Product Catalog
export const PRODUCTS = [
  {
    id: '1',
    name: 'Vermi Compost',
    price: 150,
    category: 'Fertilizer',
    description: 'Premium quality vermicompost for healthy plant growth. Rich in nutrients, improves soil structure and water retention.',
    image: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400',
    rating: 4.5,
    reviews: 128,
    weight: '1 kg',
    inStock: true,
  },
  {
    id: '2',
    name: 'Neem Cake Powder',
    price: 150,
    category: 'Pest Control',
    description: 'Organic neem cake powder acts as natural pesticide and fertilizer. Protects plants from soil-borne pests.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    rating: 4.3,
    reviews: 95,
    weight: '500 g',
    inStock: true,
  },
  {
    id: '3',
    name: 'Flower Mixture',
    price: 130,
    category: 'Fertilizer',
    description: 'Specially formulated mixture to boost flower production. Contains essential bloom-boosting nutrients.',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=400',
    rating: 4.6,
    reviews: 76,
    weight: '500 g',
    inStock: true,
  },
  {
    id: '4',
    name: 'All in One Mixture',
    price: 130,
    category: 'Multipurpose',
    description: 'Complete plant nutrition in one package. Suitable for all types of plants — indoor, outdoor, flowering & fruiting.',
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=400',
    rating: 4.7,
    reviews: 142,
    weight: '500 g',
    inStock: true,
  },
  {
    id: '5',
    name: 'Plant Booster Spray',
    price: 230,
    category: 'Spray',
    description: 'Instant plant reviver spray. Provides micronutrients directly through leaves for quick absorption.',
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400',
    rating: 4.4,
    reviews: 63,
    weight: '250 ml',
    inStock: true,
  },
  {
    id: '6',
    name: 'Flower Booster Spray',
    price: 230,
    category: 'Spray',
    description: 'Targeted spray for maximum bloom production. Encourages bud formation and vibrant flower colors.',
    image: 'https://images.unsplash.com/photo-1508610048659-a06b669e3321?w=400',
    rating: 4.5,
    reviews: 88,
    weight: '250 ml',
    inStock: true,
  },
  {
    id: '7',
    name: 'Plant Protection Spray',
    price: 230,
    category: 'Spray',
    description: 'Organic plant protection against common pests and diseases. Safe for edible plants.',
    image: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=400',
    rating: 4.2,
    reviews: 54,
    weight: '250 ml',
    inStock: true,
  },
  {
    id: '8',
    name: 'Neem Oil',
    price: 150,
    category: 'Pest Control',
    description: 'Cold-pressed pure neem oil. Natural insecticide and fungicide for organic gardening.',
    image: 'https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=400',
    rating: 4.6,
    reviews: 112,
    weight: '200 ml',
    inStock: true,
  },
  {
    id: '9',
    name: 'Root Booster',
    price: 150,
    category: 'Root Growth',
    description: 'Stimulates strong root development. Ideal for newly transplanted plants and seedlings.',
    image: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400',
    rating: 4.3,
    reviews: 47,
    weight: '250 g',
    inStock: true,
  },
  {
    id: '10',
    name: 'Plant Care Plus',
    price: 180,
    category: 'Nutrient',
    description: 'Advanced plant nutrition formula with trace elements. For lush green foliage and vigorous growth.',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    rating: 4.5,
    reviews: 69,
    weight: '500 g',
    inStock: true,
  },
];

export const CATEGORIES = [
  'All',
  'Fertilizer',
  'Pest Control',
  'Spray',
  'Multipurpose',
  'Root Growth',
  'Nutrient',
];

// Shipping rates from Lucknow
export const SHIPPING_RATES = {
  'Uttar Pradesh': 40,
  'Madhya Pradesh': 60,
  'Rajasthan': 70,
  'Delhi': 50,
  'Haryana': 60,
  'Bihar': 70,
  'Jharkhand': 80,
  'Maharashtra': 90,
  'Gujarat': 90,
  'Tamil Nadu': 120,
  'Karnataka': 110,
  'Kerala': 130,
  'West Bengal': 80,
  'Punjab': 70,
  'Uttarakhand': 50,
  'Chhattisgarh': 70,
  'Odisha': 90,
  'Assam': 120,
  'Other': 100,
};

export const FREE_SHIPPING_THRESHOLD = 1999;

export const STATES = Object.keys(SHIPPING_RATES);

export const COMMUNITY_CATEGORIES = [
  { key: 'all', label: 'All', icon: 'apps' },
  { key: 'show-tell', label: 'Show & Tell', icon: 'camera' },
  { key: 'help', label: 'Help', icon: 'help-circle' },
  { key: 'tips', label: 'Tips', icon: 'bulb' },
  { key: 'diy', label: 'DIY', icon: 'construct' },
  { key: 'balcony', label: 'Balcony', icon: 'sunny' },
  { key: 'terrace', label: 'Terrace', icon: 'home' },
  { key: 'indoor', label: 'Indoor', icon: 'leaf' },
  { key: 'organic', label: 'Organic', icon: 'nutrition' },
];

export const ORDER_STATUSES = {
  pending: { label: 'Pending', color: '#FF9800' },
  confirmed: { label: 'Confirmed', color: '#1E88E5' },
  processing: { label: 'Processing', color: '#7B1FA2' },
  shipped: { label: 'Shipped', color: '#00897B' },
  delivered: { label: 'Delivered', color: '#43A047' },
  cancelled: { label: 'Cancelled', color: '#E53935' },
};
